#!/bin/bash
MBOXES=(/home/linucc/mail/bl/archive/new /home/linucc/mail/personal/archive/new /home/linucc/mail/ostfalia/archive/new)

STATUS=""
COUNT=$(find $MBOXES -type f | wc -l)
if [ $COUNT -gt 0 ];
then
  STATUS="$COUNT"
fi

if [ "" == "$STATUS" ];
then
  echo "0"
  exit 0
else
  echo "$STATUS"
  exit 33
fi


