#!/bin/zsh

function git_branch_default() {
  if [ ! "$GIT_BRANCH_DEFAULT" = "" ]
  then
    echo "$GIT_BRANCH_DEFAULT"
  else
    echo "development"
  fi
}

function gcd() {
  git checkout $(git_branch_default)
}

function gmd() {
  git merge $(git_branch_default)
}

function settitle() {
  local title="$@"
  DISABLE_AUTO_TITLE="true"
  echo -e "\033];$title\007"
}

function downcase() {
  local var="$@"
  var=$((echo $var) | tr -c '[:alnum:] ' ' ' | tr '[:upper:]' '[:lower:]')
  var=$((echo $var) | tr -s ' ' | tr ' ' '_')
  echo $var
}

function instantfuzzy() {
  local filter="$@"
  local res=$(fzf --filter=$filter | head -n1)
  echo $res
}

function pasta() {
  $* | xsel -bi && xdotool key --clearmodifiers 'ctrl+v'
}

function cmdpasta() {
  $* | xsel -bi && xdotool key --clearmodifiers 'ctrl+shift+v'
}

function importenvfrom() {
  local filename=$1
  set -o allexport
  source "$filename"
  set +o allexport
}

function updatetime() {
  sudo ntpd -qg
}

function cdjs() {
  cd "$CODE/javascript"
}
function cdrb() {
  cd "$CODE/ruby"
}

function fbr() {
  local heads head
  heads=$(
    git for-each-ref --sort=-committerdate refs/heads/ --format='%(HEAD) %(color:yellow)%(refname:short)%(color:reset) - %(color:red)%(objectname:short)%(color:reset) - %(contents:subject) - %(authorname) (%(color:green)%(committerdate:relative)%(color:reset))'
  );
  head=$(echo "$heads" | fzf-tmux --ansi -d $(( 2 + $(wc -l <<< "$heads") )) +m) &&
    git checkout $(echo "$head" | sed "s/ - .*$//")
}
