---
- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/home/linucc/mail/personal/archive
  usual: true
  archived: false
  sync_back: true
  id: 1
  labels:
  - personal
- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/home/linucc/mail/bl/archive
  usual: true
  archived: false
  sync_back: true
  id: 2
  labels:
  - work
- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/home/linucc/mail/ostfalia/INBOX
  usual: true
  archived: false
  sync_back: true
  id: 3
  labels:
  - fh
- !supmua.org,2006-10-01/Redwood/SentLoader {}
