#!/bin/bash
MBOXES=(/home/linucc/mail/bl/archive/new /home/linucc/mail/personal/archive/new /home/linucc/mail/ostfalia/archive/new)

STATUS=""
COUNT=$(notmuch count --output=threads "tag:inbox AND NOT tag:killed")
if [ $COUNT -lt 5 ]
then
  echo "$COUNT"
  exit 0
else
  echo "$COUNT"
  exit 33
fi


