#!/usr/bin/bash

if [[ "${BLOCK_INSTANCE}" -eq "with_sync" ]]; then
  sudo pacman -Sy &> /dev/null
fi

PACKAGES=$(pacman -Qu)

URGENT_VALUE=25

if [[ $? -gt 0 ]]; then
  return
fi

PACKAGE_COUNT=$(echo -n "${PACKAGES}" | sed '/\<ignored\>/d' | wc -l)

# if [[ "${PACKAGE_COUNT}" -gt 0 ]]; then
  echo "${PACKAGE_COUNT}" # full-text
  echo "${PACKAGE_COUNT}" # short-text
  echo ""
  if [[ "${PACKAGE_COUNT}" -gt "${URGENT_VALUE}" ]]; then
    exit 33
  fi
# fi
